on:
  push:
    branches:

jobs:
  luciferous_helix:
    runs-on: ubuntu-latest
    container:
      image: qmkfm/qmk_cli
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: qmk setup --yes
      - run: ll -lF
      - run: qmk compile -kb helix/rev3 -km default
      - run: ll -lF
      # - uses: actions/upload-artifact@v5
      #   with:
      #     path: .build/

